### ISSUE TITLE
New file format

### ISSUE THREAD

**Issue by justinbois** [justinbois/fish-activity#12]
@grigorios-oikonomou, you mentioned that there is a new file format. Can you please send me a sample file via email?

**Comment by grigorios-oikonomou** [comment]
I am sending the files through dropbox.

The new file (170606_7A_7B.XLS) is from a machine with only one box (it's a demo). The "location" column and the "animal" column is a bit different. Compare to the old file (170420_5A_5B.XLS) from another single box machine. The "location" is the relevant column for identifying fish (not the "animal" column), since conceptually the only thing we know about the animal is in which well we put it.

The differences between the two files appear trivial. I tried changing them but both the perl script we use for the old package, and the new python based package are not able to handle the new file.

You can use the fake genotype file (fake as in no genotyping was actually done; this was a trial run) "170607_7A_genotype_1.txt".

**Comment by justinbois** [comment]
I added the capability to handle the new file format. The new format has differences in how it labels the locations in the wells and the animals. The animals are labeled like `G07` for the animal in row G, column 7 of the plate. The locations are labeled like `c1-006` for position 6 in well 1 (I think). The numbers of the locations go up to `096`.

We will need to revisit this for a two-sample machine. The current parser will work if the `location` field for the new plate is `c1-108` or `c2-108`, but it will break if it is `c2-012`. So, I'll leave this issue open until we verify that the two-plate system has a compatible location numbering system.

**Comment by grigorios-oikonomou** [comment]
The activity plot works great with the new file format, but I am having trouble with the sleep plot. The sleep plot still works great for the file format.

**Comment by justinbois** [comment]
I'm not sure what you mean by the sleep plot. Can you expand on this?

**Comment by grigorios-oikonomou** [comment]
When I try to graph sleep instead of activity I get a flat line. It actually turns out that the settings on the instrument were messed up and always give me some activity. So the error is in the acquisition, not the analysis. Feel free to close this issue!

**Comment by justinbois** [comment]
Ok, will address this issue soon.

**Comment by justinbois** [comment]
Completed.
